server:
  port: 8080

# PostgreSQL DataSource Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/courierdb
    username: courieruser
    password: courierpassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  # Logging Configuration
  #logging:
  #  level:
  #    root: DEBUG


  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 180000


